# generated by datamodel-codegen:
#   filename:  archivos.json
#   timestamp: 2025-11-11T19:03:18+00:00

from __future__ import annotations

from pydantic import BaseModel


class Archivo(BaseModel):
    nombre: str
    tipo: str
    enlace: str
